package co.pitayagroup.mcp.broadworks.mcp;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.IOException;
import java.net.SocketTimeoutException;
import java.net.UnknownHostException;
import java.nio.file.Files;
import java.nio.file.Path;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

/**
 * Covers the report produced when a BroadWorks host fails to resolve (the ECS
 * {@code UnknownHostException: <host>: Temporary failure in name resolution} case).
 */
class DnsDiagnosticsTest {

    @TempDir
    Path tempDir;

    @Test
    void detectsNameResolutionFailureAnywhereInTheCauseChain() {
        final Throwable wrapped = new IllegalStateException("connect failed",
                new IOException("io", new UnknownHostException("portal.vwave.net: Temporary failure in name resolution")));

        assertThat(DnsDiagnostics.isNameResolutionFailure(wrapped)).isTrue();
    }

    @Test
    void doesNotMistakeOtherConnectionFailuresForResolutionFailures() {
        assertThat(DnsDiagnostics.isNameResolutionFailure(
                new IOException("read timed out", new SocketTimeoutException()))).isFalse();
        assertThat(DnsDiagnostics.isNameResolutionFailure(null)).isFalse();
    }

    @Test
    void reportsTheConfiguredNameserversAndSearchDomains() throws Exception {
        final Path resolvConf = Files.writeString(tempDir.resolve("resolv.conf"), """
                # Generated by the container runtime
                nameserver 169.254.169.253
                search us-east-1.compute.internal
                options ndots:5
                """);

        assertThat(DnsDiagnostics.resolverConfig(resolvConf))
                .isEqualTo("nameserver 169.254.169.253; search us-east-1.compute.internal; options ndots:5");
    }

    @Test
    void reportsAnUnreadableOrEmptyResolverConfigurationInsteadOfFailing() throws Exception {
        final Path missing = tempDir.resolve("absent.conf");
        assertThat(DnsDiagnostics.resolverConfig(missing)).contains(missing.toString(), "unreadable");

        final Path empty = Files.writeString(tempDir.resolve("empty.conf"), "# nothing here\n");
        assertThat(DnsDiagnostics.resolverConfig(empty)).contains("no nameserver configured");
    }

    @Test
    void derivesTheRegistrableParentDomainOnlyWhenItAddsInformation() {
        assertThat(DnsDiagnostics.parentDomain("portal.vwave.net")).isEqualTo("vwave.net");
        assertThat(DnsDiagnostics.parentDomain("as1.cluster.portal.vwave.net")).isEqualTo("vwave.net");
        // Nothing to compare against: an apex, an IP literal or an empty host.
        assertThat(DnsDiagnostics.parentDomain("vwave.net")).isNull();
        assertThat(DnsDiagnostics.parentDomain("216.128.192.41")).isNull();
        assertThat(DnsDiagnostics.parentDomain("2001:db8::1")).isNull();
        assertThat(DnsDiagnostics.parentDomain("  ")).isNull();
        assertThat(DnsDiagnostics.parentDomain(null)).isNull();
    }

    @Test
    void lookupReportsTheResolversVerdictForAnUnresolvableName() {
        // .invalid is reserved by RFC 2606 and never resolves, so this needs no network.
        assertThat(DnsDiagnostics.lookup("broadworks-mcp-does-not-exist.invalid")).startsWith("failed(");
        assertThat(DnsDiagnostics.lookup("localhost")).startsWith("ok(");
    }

    @Test
    void describeCombinesResolverConfigurationWithBothLookups() throws Exception {
        final Path resolvConf = Files.writeString(tempDir.resolve("resolv.conf"), "nameserver 10.0.0.2\n");

        final String report = DnsDiagnostics.describe("portal.example.invalid", resolvConf);

        assertThat(report)
                .contains("resolver=[nameserver 10.0.0.2]")
                .contains("lookup(portal.example.invalid)=failed(")
                .contains("lookup(example.invalid)=failed(");
    }
}
